services:
  database:
    image: postgres:16
    restart: always
    container_name: database
    command:
      - -p ${DB__PORT}
    expose:
      - ${DB__PORT}
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: app
    command: [ "src/scripts/app.sh" ]
    env_file:
      - src/environs/.env.prod
    ports:
      - ${RUN__PORT}:${RUN__PORT}
    depends_on:
      - database

volumes:
  db-data:
    name: ${VOLUMES_SOURCE}
