services:
  database:
    image: postgres:16
    restart: always
    container_name: database
    ports:
      - ${DB__PORT}:5432
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data

volumes:
  db-data:
    name: ${VOLUMES_SOURCE}
